POST http://localhost:3003/criar/turma
Content-Type: application/json

{
    "nome":"cruz"
}

###

GET http://localhost:3003/buscar/turmas/ativas

###

POST http://localhost:3003/muda/turma/modulo
Content-Type: application/json
 
{
    "IdTurma":"2",
    "modulo":"3"
}

###

POST http://localhost:3003/criar/estudante
Content-Type: application/json

{
    "nome": "Mario",
	"email": "mario@gmail.com",
    "dataNascimento": "1981-07-09",
    "turmaId": "1"
}

###

GET http://localhost:3003/estudante/maria

###

POST http://localhost:3003/muda/estudante/turma
Content-Type: application/json

{
    "IdEstudante":"02",
    "idTurma":"1"
}

###

POST http://localhost:3003/criar/docente
Content-Type: application/json

{
    "nome": "Thiago",
	"email": "thiago@gmail.com",
    "dataNascimento": "2003-04-15",
    "turmaId": "001"
}


###

GET http://localhost:3003/buscar/docentes

###

POST http://localhost:3003/muda/docente/turma
Content-Type: application/json

{
    "IdDocente":"1662730733851",
    "idTurma":"001"
}

