POST http://localhost:3003/criar/turma
Content-Type: application/json

{
    "nome":"Jacs"
}

###

GET http://localhost:3003/buscar/turmas/ativas

###

POST http://localhost:3003/muda/turma/modulo
Content-Type: application/json
 
{
    "turmaId":"1",
    "modulo":"1"
}

###

POST http://localhost:3003/criar/estudante
Content-Type: application/json

{
    "nome": "Lulu",
	"email": "lulu@gmail.com",
    "dataNascimento": "20/08/2000",
    "turmaId": "2"
}

###

GET http://localhost:3003/estudante/lulu

###

POST http://localhost:3003/muda/estudante/turma
Content-Type: application/json

{
    "IdEstudante":"02",
    "turmaId":"3"
}

###

POST http://localhost:3003/criar/docente
Content-Type: application/json

{
    "nome": "Timão",
	"email": "timao@gmail.com",
    "dataNascimento": "2000/02/10",
    "turmaId": "1662744758401"
}


###

GET http://localhost:3003/buscar/docentes

###

POST http://localhost:3003/muda/docente/turma
Content-Type: application/json

{
    "IdDocente":"003",
    "turmaId":"1"
}

